# Generated by Django 5.2.14 on 2026-05-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
